GET http://127.0.0.1/api/users HTTP/1.1

###

POST http://127.0.0.1/api/categories HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzU4MDM2NCwianRpIjoiOWZmYTEzZjctYTYwNi00MmMxLTk5YTAtYjFlZmU4YzNkZDI1IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Inplcm8iLCJuYmYiOjE3MDc1ODAzNjQsImNzcmYiOiI5Y2UwMjUyZS02MDk3LTRiOTctYTE5Yy1lZDBlYjQ2OWEwYjgiLCJleHAiOjE3MDc1ODM5NjR9.8FMd6ZGMMNRgxx0EkK9DoaA9B_1qCKBdBhqHgBO7hcs
Content-Type: application/json

{
    "category_name": "Uniandes"
}

###

POST http://127.0.0.1/users HTTP/1.1
Content-Type: application/json

{
    "username": "zero",
    "password": "pass"
}

###

POST http://127.0.0.1/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "zero",
    "password": "pass"
}

###

GET http://127.0.0.1/protected HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzQwMjQ0NCwianRpIjoiNmI4OTUwYjEtYjE2MC00ZmJkLWIxNTEtNDdmNDAzYjdjMDhhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Inplcm8iLCJuYmYiOjE3MDc0MDI0NDQsImNzcmYiOiJhOWQ0MzFkOS1hMWE0LTQ2OTUtYTAxZC05NmJiNjUwYjRhODQiLCJleHAiOjE3MDc0MDYwNDR9.YigUderRRU9T8npBKYTh8CUfnWh9uG37TdX1VmhNhp0

###

GET http://127.0.0.1/api/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzQwMjQ0NCwianRpIjoiNmI4OTUwYjEtYjE2MC00ZmJkLWIxNTEtNDdmNDAzYjdjMDhhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Inplcm8iLCJuYmYiOjE3MDc0MDI0NDQsImNzcmYiOiJhOWQ0MzFkOS1hMWE0LTQ2OTUtYTAxZC05NmJiNjUwYjRhODQiLCJleHAiOjE3MDc0MDYwNDR9.YigUderRRU9T8npBKYTh8CUfnWh9uG37TdX1VmhNhp0

###

POST http://127.0.0.1/tasks HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzQwMjQ0NCwianRpIjoiNmI4OTUwYjEtYjE2MC00ZmJkLWIxNTEtNDdmNDAzYjdjMDhhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6Inplcm8iLCJuYmYiOjE3MDc0MDI0NDQsImNzcmYiOiJhOWQ0MzFkOS1hMWE0LTQ2OTUtYTAxZC05NmJiNjUwYjRhODQiLCJleHAiOjE3MDc0MDYwNDR9.YigUderRRU9T8npBKYTh8CUfnWh9uG37TdX1VmhNhp0
Content-Type: application/json

{
    "task_title": "Tarea 2",
    "task_category": "Uniandes",
    "task_description": "Hacer la tarea 2",
    "date_to_end": "2024-02-02"
}